general:
  exclude_genre: animation, documentary
  limit_plex_results: 5
  limit_trakt_results: 5
  plex_only: false
  show_summary: true
  keep_logs: 10
  confirm_operations: true
paths:
  path_mappings: null
  platform: windows
plex:
  add_label: true
  label_name: RecommendedMovies
  library_title: TV Shows
  remove_previous_recommendations: true
  token: YOUR_PLEX_TOKEN
  url: http://localhost:32400
radarr:
  add_to_radarr: true
  api_key: YOUR_RADARR_API_KEY
  monitor: true
  quality_profile: HD-1080p
  radarr_tag: RecommendedMovies
  root_folder: P:\Movies
  url: http://localhost:7878
trakt:
  access_token: 
  client_id: YOUR_TRAKT_CLIENT_ID
  client_secret: YOUR_TRAKT_SECRET
TMDB:
  use_TMDB_keywords: true
  api_key: YOUR_TMDB_API_KEY